name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Add Hugging Face remote and push to Spaces
        env:
          HF_TOKEN: ${{ secrets.CASE_STUDY_1_SECRET }}  # Use the stored Hugging Face token
        run: |
          git remote add space https://huggingface.co/spaces/BashirG/dis-background-removal-duplicated
          git push --force "https://huggingface.co:${HF_TOKEN}@huggingface.co/spaces/BashirG/dis-background-removal-duplicated" main
