name: Server Monitoring and Auto-Recovery

on:
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:        

jobs:
  check-server:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Secondary SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STUDENT_GEN }}
        ssh-private-key2: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Store New SSH Key and Public Key in Files
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > mykey
        chmod 600 mykey
        echo "${{ secrets.NEW_SSH_PUBLIC_KEY }}" > mykey.pub

    - name: Store Old SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_STUDENT_GEN }}" > secondary_key
        chmod 600 secondary_key
        
    - name: Check and Recover Server
      run: |
        PORT=22040
        MACHINE="paffenroth-23.dyn.wpi.edu"
        REPO_URL="https://github.com/Bashir1999/products.git"
        PROJECT_DIR="products"
        APP_FILE="app.py"
        
        log() {
            echo "[INFO] $1"
        }
        log "Checking if SSH connection with key works..."
        ssh -i mykey -p "${PORT}" -o StrictHostKeyChecking=no -o student-admin@"${MACHINE}" 
        log "SSH connection with key works. Proceeding with the deployment steps."
        
